package edu.cnm.deepdive.escaperoom.model.entity;


import android.arch.persistence.room.ColumnInfo;
import android.arch.persistence.room.Entity;
import android.arch.persistence.room.Index;
import android.arch.persistence.room.PrimaryKey;

/**
 * This is the User Table that was intended to keep information from the user as a means to
 * separate history between users. It is not being used at this moment. In hindsight it
 * would be better to implement Google Sign in to deal with users.
 */
@Entity(indices = {
    @Index("user_id"), @Index("name")})
public class User {

  @PrimaryKey(autoGenerate = true)
  @ColumnInfo(name = "user_id")
  private long userID;

  @ColumnInfo
  private String name;

  /**
   * Returns the autogenerated primary key of this instance.
   *
   * @return primary key value.
   */
  public long getUserID() {
    return userID;
  }

  /**
   * Sets the scenario Id  of this instance. This method is invoked by Room when
   * loading the instance from the database.
   *
   * @param userID long userId.
   */

  public void setUserID(long userID) {
    this.userID = userID;
  }


  /**
   * Returns the name of this instance.
   *
   * @return name.
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the name  of this instance. This method is invoked by Room when
   * loading the instance from the database.
   *
   * @param name String name.
   */

  public void setName(String name) {
    this.name = name;
  }
}
